spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event-top-dev
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: false

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
      enabled: false

#  mvc:
#    static-path-pattern=/static/**

server:
  port: 80
  host: